version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/CurlToCSharp"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "weekly"
      
