version: 1.0.{build}
image: Ubuntu2004
services:
- docker
stack: node 14, jdk 11
environment:
  CYPRESS_RECORD_KEY:
    secure: zrEJrmRw4T8jXDP0u73B73A8QEfq6bRi1Z9F4d7bEumJK9sZVyW/KUG2qN1WWYeL
install:
  - dotnet tool install -g Cake.Tool --version 1.1.0
  - npm install --global gulp-cli
build_script:
- dotnet cake --Target=Test
test: off
cache:
  - 'src/CurlToCSharp/node_modules/ -> src\CurlToCSharp\yarn.lock'
  - 'tools -> build.cake'
  - '%USERPROFILE%/.nuget/packages -> **\*.csproj'
  - '%USERPROFILE%/.sonar/cache'
  - '%USERPROFILE%/.cache/Cypress -> src\CurlToCSharp\yarn.lock'

for:
  branches:
  only:
    - master

  build_script:
  - dotnet cake --Target=CI --cypressConfigurationFile=cypress.production.json --cypressEnableRecording=true

  deploy:
  - provider: AzureAppServiceZipDeploy
    website: curltocsharp
    username: CurlToCSharp
    password:
      secure: anNXyv5QGtXmsPV21/COiAolYBhLYF8Pi3yWd/qIRd4=
