version: 1.0.{build}
image: Visual Studio 2019
skip_branch_with_pr: true
environment:
  CYPRESS_RECORD_KEY:
    secure: zrEJrmRw4T8jXDP0u73B73A8QEfq6bRi1Z9F4d7bEumJK9sZVyW/KUG2qN1WWYeL
install:
  - choco install curl
  - dotnet tool install -g Cake.Tool --version 0.38.5
  - SET JAVA_HOME=C:\Program Files\Java\jdk11
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - ps: Install-Product node 14
build_script:
- cmd: dotnet cake -Target=CI
test: off
deploy:
- provider: AzureAppServiceZipDeploy
  website: curltocsharp
  username: CurlToCSharp
  password:
    secure: anNXyv5QGtXmsPV21/COiAolYBhLYF8Pi3yWd/qIRd4=
after_deploy:
  - cd src\CurlToCSharp
  - yarn run cypress run --config-file cypress.production.json --record
cache:
  - '%USERPROFILE%\.sonar\cache'
  - 'src\CurlToCSharp\node_modules\ -> src\CurlToCSharp\yarn.lock'
  - '%LOCALAPPDATA%\Yarn\cache -> src\CurlToCSharp\yarn.lock'
  - '%LOCALAPPDATA%\Cypress\Cache -> src\CurlToCSharp\yarn.lock'
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - 'C:\ProgramData\chocolatey\lib -> appveyor.yml'
  - 'tools -> build.cake'
