version: 1.0.{build}
image: Ubuntu2004
services:
- docker
environment:
  CYPRESS_RECORD_KEY:
    secure: zrEJrmRw4T8jXDP0u73B73A8QEfq6bRi1Z9F4d7bEumJK9sZVyW/KUG2qN1WWYeL
install:
  - dotnet tool install -g Cake.Tool --version 1.1.0
  - nvm use 14.17.0
build_script:
- dotnet cake --Target=CI --cypressConfigurationFile=cypress.production.json --cypressEnableRecording=true
test: off
deploy:
- provider: AzureAppServiceZipDeploy
  website: curltocsharp
  username: CurlToCSharp
  password:
    secure: anNXyv5QGtXmsPV21/COiAolYBhLYF8Pi3yWd/qIRd4=
cache:
  - 'src\CurlToCSharp\node_modules\ -> src\CurlToCSharp\yarn.lock'
  - 'tools -> build.cake'
